# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    target-branch: experiment
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      web-minor:
        update-types: [minor, patch]

  - package-ecosystem: gradle
    directory: "/apps/desktop"
    schedule:
      interval: weekly
    target-branch: experiment
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: experiment
    commit-message:
      prefix: "ci(deps)"
